"""Company registry for the LATAM pipeline.

Provides:
  - CompanyRecord: dataclass representing a LATAM company
  - make_slug(): deterministic ASCII slug from Unicode company names
  - make_storage_path(): creates data/latam/{country}/{slug}/ directory
  - write_meta_json(): writes meta.json to a company's storage directory

The slug is the permanent filesystem key for every LATAM company. It must be
deterministic, Windows NTFS-safe, and generated from Unicode Spanish/Portuguese
names.

The storage layout mirrors the US pipeline schema (data/clean/{ticker}/) so
that existing dashboard code works without modification — LATAM companies live
at data/latam/{country}/{slug}/ instead.

References:
  - RESEARCH.md Pattern 2 (slug generation via python-slugify)
  - RESEARCH.md Pattern 4 (storage layout and meta.json schema)
"""

import json
from dataclasses import dataclass, field
from pathlib import Path

from slugify import slugify  # python-slugify — must be installed: pip install python-slugify

# ---------------------------------------------------------------------------
# Schema constants — exact column order as found in data/clean/AAPL/financials.parquet
# LATAM companies must produce Parquet files with identical column names/dtypes
# so the dashboard layer needs no modification.
# ---------------------------------------------------------------------------

EXPECTED_FINANCIALS_COLS: list[str] = [
    "ticker",
    "fiscal_year",
    "revenue",
    "gross_profit",
    "cogs",
    "operating_income",
    "net_income",
    "interest_expense",
    "depreciation_amortization",
    "total_assets",
    "total_liabilities",
    "total_equity",
    "current_assets",
    "current_liabilities",
    "cash",
    "short_term_investments",
    "receivables",
    "inventory",
    "long_term_debt",
    "short_term_debt",
    "accounts_payable",
    "shares_outstanding",
    "operating_cash_flow",
    "capex",
]

EXPECTED_KPIS_COLS: list[str] = [
    "ticker",
    "fiscal_year",
    "revenue_growth_yoy",
    "revenue_cagr_10y",
    "gross_profit_margin",
    "operating_margin",
    "net_profit_margin",
    "ebitda_margin",
    "roe",
    "roa",
    "current_ratio",
    "quick_ratio",
    "cash_ratio",
    "working_capital",
    "debt_to_equity",
    "debt_to_ebitda",
    "interest_coverage",
    "debt_to_assets",
    "asset_turnover",
    "inventory_turnover",
    "dso",
    "cash_conversion_cycle",
]


# ---------------------------------------------------------------------------
# CompanyRecord dataclass
# ---------------------------------------------------------------------------

@dataclass
class CompanyRecord:
    """Metadata record for a single LATAM company.

    Fields
    ------
    company_name : str
        Full Unicode display name (e.g. "Clínica Las Américas").
    slug : str
        ASCII filesystem key generated by make_slug() (e.g. "clinica-las-americas").
    country : str
        Lowercase country name (e.g. "colombia", "peru").
    regulatory_id : str
        NIT / RUC / RUT identifier as published by the regulatory authority.
    regulatory_authority : str
        Authority that published the filing (e.g. "Supersalud", "SMV", "CMF").
    source_url : str
        URL of the source document or portal page.
    currency_original : str
        Three-letter ISO currency code as reported (e.g. "COP", "BRL", "ARS").
    approximated_fx : bool
        True when the FX rate used is an approximation (annual average).
    low_confidence_fx : bool
        True for ARS and other currencies with volatile/unofficial rates.
        See RESEARCH.md Pitfall 3 and v2.0 Roadmap FX decision.
    """

    company_name: str
    slug: str
    country: str
    regulatory_id: str
    regulatory_authority: str
    source_url: str
    currency_original: str
    approximated_fx: bool = field(default=False)
    low_confidence_fx: bool = field(default=False)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def make_slug(company_name: str) -> str:
    """Return a deterministic, ASCII-only, Windows-safe slug for *company_name*.

    Uses python-slugify with allow_unicode=False to force ASCII transliteration.
    This converts accented characters (á→a, ñ→n, ü→u, etc.) and strips all
    characters that are unsafe on Windows NTFS (parentheses, dots, slashes, etc.).

    Examples
    --------
    >>> make_slug("Clínica Las Américas")
    'clinica-las-americas'
    >>> make_slug("EPS Sánitas (NUEVA)")
    'eps-sanitas-nueva'
    >>> make_slug("Organización Sanitas S.A.")
    'organizacion-sanitas-s-a'

    WARNING: Do NOT use allow_unicode=True here. Unicode directory names can
    cause encoding issues on Windows NTFS and are not portable across OS locales.
    See RESEARCH.md Pitfall 4.
    """
    return slugify(company_name, allow_unicode=False, separator="-")


def make_storage_path(base_dir: Path, country: str, slug: str) -> Path:
    """Create and return the storage directory for a LATAM company.

    Directory structure: base_dir / "latam" / country.lower() / slug

    This mirrors the US pipeline layout (data/clean/{ticker}/) so that
    dashboard code reading data/latam/{country}/{slug}/financials.parquet
    uses the same logic as data/clean/AAPL/financials.parquet.

    Parameters
    ----------
    base_dir : Path
        Project data root (typically Path("data")).
    country : str
        Country name — will be lowercased (e.g. "Colombia" → "colombia").
    slug : str
        Company slug from make_slug().

    Returns
    -------
    Path
        The created directory path.
    """
    path = base_dir / "latam" / country.lower() / slug
    path.mkdir(parents=True, exist_ok=True)
    return path


def write_meta_json(path: Path, record: CompanyRecord) -> None:
    """Write meta.json to *path* / "meta.json" from a CompanyRecord.

    The JSON schema is defined in RESEARCH.md Pattern 3 and includes all
    CompanyRecord fields plus pipeline tracking fields (last_scraped,
    last_processed, fiscal_years_available, extraction_quality, etc.).

    Parameters
    ----------
    path : Path
        Directory where meta.json will be written (the company's storage dir).
    record : CompanyRecord
        The company metadata to serialise.

    Notes
    -----
    ensure_ascii=False preserves Unicode in display names (company_name) so
    that meta.json is human-readable without escape sequences.
    """
    meta = {
        "company_name": record.company_name,
        "slug": record.slug,
        "country": record.country,
        "regulatory_id": record.regulatory_id,
        "regulatory_authority": record.regulatory_authority,
        "source_url": record.source_url,
        "currency_original": record.currency_original,
        "approximated_fx": record.approximated_fx,
        "low_confidence_fx": record.low_confidence_fx,
        "last_scraped": None,
        "last_processed": None,
        "fiscal_years_available": [],
        "extraction_quality": None,
        "fields_extracted": [],
        "fields_missing": [],
    }
    (path / "meta.json").write_text(
        json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8"
    )
